import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {

  const latestUser = api.post.getLatestUser.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <p className="text-lg font-semibold">
            Latest Github User:

            {latestUser.data && (
              <>
                <span className="text-blue-500">
                  {`${latestUser.data.login ? latestUser.data.login : 'loading'} `}
                </span>
                <br />
                <span className="text-gray-500">
                  {`Name: ${latestUser.data.name}`}
                </span>
                <br />
                <span className="text-gray-500">
                  {`Avatar:`}
                  <img width={100} height={100} className="rounded-full" src={latestUser.data.avatarUrl ?? ''} alt="avatar" />
                </span>
              </>
            )}
          </p>
        </div>
      </main>
    </>
  );
}